[DEFAULT]
enabled_backends = nfs-orionsbelt

[nfs-orionsbelt]
volume_driver = cinder.volume.drivers.nfs.NfsDriver
nfs_shares_config = /etc/cinder/nfs_shares
volume_backend_name = nfs-orionsbelt
nfs_snapshot_support = true
